### ISSUE TITLE
Revise FAQ

### ISSUE THREAD

**Issue by undocumentedhuman** [Bit-Nation/Pangea-Docs#1]
Will BITNATIONS IDs allow me to cross borders. 

I'd like to suggest that this part be edited. 

Currently the BITNATION ID is compatible with EU regulations. It can and has been used to enable Stateless people access to private services. It is possible that as BITNATION gains significant market adoption and as it becomes the norm, more people will be able to use the BITNATION ID while traveling. The Pangea Jurisdiction brings governance choices to your home, (in your phone or on your computer!), regardless of what country you were born in, where you live, or what passport you hold. Furthermore, there are individuals, currently working as BITNATION citizens, ambassadors, and nations, to gain mass adoption of BITNATION IDs as well as documentation of property such as sailboats and automobiles.

**Comment by xsttx** [comment]
Thanks, I'll update it. In the future please highlight the changed/ added or deleted words or sentences in **bold** or _italic_ so it's easier to review.
