### ISSUE TITLE
P. 5, items 4 - 6: Listing of services (as per items 1 - 3) instead of as accomplishments;

### ISSUE THREAD

**Issue by kosanke** [Bit-Nation/Pangea-Docs#10]
Bitnation organized the world’s first 4. Bitnation organized the world’s first Blockchain Marriage and World Citizenship ID, Blockchain Land Title, Birth Certificate and Refugee Emergency ID during 2014 and 2015. 

becomes 

4. Blockchain Marriages, World Citizenship IDs, Blockchain Land Titles, Birth Certificates, and Refugee Emergency IDs (Bitnation organized all of these in 2014 and 2015.);

**Comment by jofster** [comment]
4.	Blockchain Marriage (the world’s first), World Citizenship ID, Blockchain Land Title, Birth Certificate and Refugee Emergency ID all organized during 2014 and 2015.
