### ISSUE TITLE
P 7 Par 4: Note: A DBVN may be a governing entity but not a compulsory geographical or ethnocentric monopoly.

### ISSUE THREAD

**Issue by kosanke** [Bit-Nation/Pangea-Docs#20]
Nation: A nation is a large group of people who share a common language, culture,
ethnicity, descent, or history. In the case of ~~DBVN’s~~ **DBVNs,** it is likely that people would be as
connected through mutual interests and goals as they ~~would~~ **are in** more traditional commonalities such as culture and language. A ~~nation~~ **DBVN** is a voluntary formation rather than a ~~governing entity~~ **compulsory geographical or ethnocentric monopoly** (i.e. a state). ~~We provide~~ **Bitnation provides** the tools for governance but ~~do~~ **does** not impose them, nor do we impose any specific code of law or regulations.

**Comment by jofster** [comment]
Apostrophe removed
