### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by kosanke** [Bit-Nation/Pangea-Docs#5]
"hen" should be "when"

The Pangea Arbitration Token (PAT) is an ERC20 compatible in-app token for the Pangea
Jurisdiction. The PAT token rewards good reputation, and is issued on Pangea **hen** Citizens
accumulate non-tradable reputation tokens through creating a contract, successfully completing a
contract or resolving a dispute attached to a contract. PAT is an algorithmic reputation token; an
arbitration currency based on performance, rather than purchasing power, popularity, or
attention.

**Comment by xsttx** [comment]
@kosanke please add page and paragraph number so it's easier to track

**Comment by kosanke** [comment]
page 2 Paragraph 2

**Comment by jofster** [comment]
got it

**Comment by jofster** [comment]
this can be closed
