### ISSUE TITLE
p 5 par 1: remove comma, move "and"

### ISSUE THREAD

**Issue by kosanke** [Bit-Nation/Pangea-Docs#8]
We have over 100 Embassies ~~,~~ and

<enter Pangea_ bitnation.co 5
Consulates, ~~and~~ over 10,000 Citizens on all five continents, **and** a dynamic community of 2000
contributors on our Slack channel. We offer a range of services in-house or in partnership with
other providers.

**Comment by jofster** [comment]
got it
