### ISSUE TITLE
p 5 par 2: Move dash, add semicolon, and add comma after "agreements".

### ISSUE THREAD

**Issue by kosanke** [Bit-Nation/Pangea-Docs#9]
1. The Bitnation blockchain Public Notary **-** which is being used for a wide range of purposes**;** <-
marriages, wills, birth certificates, company registration, land titles, freelance agreements,
loan agreements**,** and so on;

**Comment by kosanke** [comment]
1. The Bitnation blockchain Public Notary which is being used for a wide range of purposes -
marriages, wills, birth certificates, company registration, land titles, freelance agreements,
loan agreements and so on;

becomes 

1. The Bitnation blockchain Public Notary - which is being used for a wide range of purposes;
marriages, wills, birth certificates, company registration, land titles, freelance agreements,
loan agreements, and so on;

**Comment by jofster** [comment]
for consistency, changed to:

1.	The Bitnation blockchain Public Notary, which is being used for a wide range of purposes including marriages, wills, birth certificates, company registration, land titles, freelance agreements, loan agreements and so on;
